name: http
version: 0.12.3-nullsafety
homepage: https://github.com/dart-lang/http
description: A composable, multi-platform, Future-based API for HTTP requests.

environment:
  sdk: '>=2.10.0-0 <2.11.0'

dependencies:
  http_parser: ^3.2.0-nullsafety
  path: ^1.8.0-nullsafety.1
  pedantic: ^1.10.0-nullsafety

dev_dependencies:
  test: ^1.16.0-nullsafety.4

dependency_overrides:
  http_parser:
    git: https://github.com/dart-lang/http_parser
